apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-global-user-binding
subjects:
- kind: User
  name: dev-joao
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: viewer-global
  apiGroup: rbac.authorization.k8s.io