apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  containers:
  # Container que escreve dados
  - name: writer
    image: alpine
    command: ["/bin/sh", "-c", "echo 'Dados importantes' > /data/arquivo.txt && sleep 3600"]
    volumeMounts:
    - name: dados
      mountPath: /data

  # Container que lê os mesmos dados
  - name: reader
    image: alpine
    command: ["/bin/sh", "-c", "sleep 10 && cat /data/arquivo.txt && sleep 3600"]
    volumeMounts:
    - name: dados
      mountPath: /data

  # Volume emptyDir compartilhado entre os containers
  volumes:
    - name: dados
      emptyDir: {}