apiVersion: v1
kind: Pod
metadata:
  name: pod-dinamico
spec:
  nodeSelector:
    kubernetes.io/hostname: fundamentos-kubernetes-control-plane
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: app
    image: alpine
    command:
      - /bin/sh
      - -c
      - "echo 'Storage local com WaitForFirstConsumer' > /dados/aula.txt && sleep 3600"
    volumeMounts:
    - name: storage
      mountPath: /dados
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-dinamico