apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
spec:
  containers:
  - name: container-sc
    image: nginx
    volumeMounts:
    - name: volume-sc
      mountPath: /volume-dentro-do-container
  volumes:
  - name: volume-sc
    persistentVolumeClaim:
      claimName: pvc-2