apiVersion: v1
kind: Pod
metadata:
  name: pod-con-pvc
spec:
  containers:
  - name: app
    image: alpine:3.18
    command: ["sleep", "3600"]
    volumeMounts:
    - name: storage
      mountPath: /dados
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-exemplo