apiVersion: v1
kind: Pod
metadata:
  name: pod-con-configmap
spec:
  containers:
  - name: app
    image: alpine:3.18
    command: ["sleep", "3600"]
    # Variaveis de ambiente vindas do ConfigMap
    env:
      - name: AMBIENTE
        valueFrom:
          configMapKeyRef:
            name: config-app
            key: APP_ENV
    # Arquivos de configuração montados como volume
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: config-app